# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connexion.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import model
import time
from error.error import error 
import generateind as generateind
from main1 import main


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 825)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Minimalistic-Flat-Modern-GUI-Template-master/Minimalistic-Flat-Modern-GUI-Template-master/images/Layout/frontpageAsset 1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(110, 190, 861, 491))
        self.widget.setObjectName("widget")
        self.leftpanel = QtWidgets.QFrame(self.widget)
        self.leftpanel.setGeometry(QtCore.QRect(-1, 0, 441, 501))
        self.leftpanel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-image: url(\'C:/Users/pukut/Downloads/8149502_3823526.svg\'); \n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"background-size: cover;")
        self.leftpanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftpanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftpanel.setObjectName("leftpanel")
        self.signinbutton = QtWidgets.QPushButton(self.leftpanel)
        self.signinbutton.setGeometry(QtCore.QRect(100, 380, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.signinbutton.setFont(font)
        self.signinbutton.clicked.connect(self.signin) 
        self.signinbutton.setStyleSheet("background:rgb(116,116,116);\n"
"color: white;\n"
"border-radius: 20px;\n"
"padding: 5px;")
        
        self.signinbutton.setObjectName("signinbutton")
        self.label_5 = QtWidgets.QLabel(self.leftpanel)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: transparent;\n"
"color: blue;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.leftpanel_2 = QtWidgets.QFrame(self.widget)
        self.leftpanel_2.setGeometry(QtCore.QRect(440, 0, 421, 491))
        self.leftpanel_2.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(116,116,116);")
        self.leftpanel_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftpanel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftpanel_2.setObjectName("leftpanel_2")
        self.label = QtWidgets.QLabel(self.leftpanel_2)
        self.label.setGeometry(QtCore.QRect(0, 40, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("color:rgb(116, 116, 116);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(5)
        self.label.setMidLineWidth(5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.leftpanel_2)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.leftpanel_2)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(self.leftpanel_2)
        self.username.setGeometry(QtCore.QRect(60, 200, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.username.setFont(font)
        self.username.setStyleSheet("border:none;\n"
"border-bottom: 4px solid rgb(115, 115, 115) ;")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.leftpanel_2)
        self.password.setGeometry(QtCore.QRect(60, 300, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password.setFont(font)
        self.password.setStyleSheet("border:none;\n"
"border-bottom: 4px solid rgb(115, 115, 115) ;\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_4 = QtWidgets.QLabel(self.leftpanel_2)
        self.label_4.setGeometry(QtCore.QRect(210, 440, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.loginbutton = QtWidgets.QPushButton(self.leftpanel_2)
        self.loginbutton.setGeometry(QtCore.QRect(80, 370, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.loginbutton.setFont(font)

        self.loginbutton.setStyleSheet(""" 
                                QPushButton { 
                                        background-color: rgb(6, 6, 6);
                                        color: white; 
                                        border: none;
                                        padding: 10px 20px; 
                                        text-align: center;
                                        text-decoration: none; 
                                        display: inline-block; 
                                        font-size: 16px;
                                        margin: 4px 2px;
                                        cursor: pointer;
                                        border-radius: 20px; } 
                                QPushButton:hover { background-color:  rgb(55, 55, 155);  } 
                                 QPushButton:pressed { background-color:  rgb(55, 55, 155); } """)




#         self.loginbutton.setStyleSheet("background-color: rgb(116, 116, 116);\n"
# "color: rgb(6, 6, 6);\n"
# "border-radius: 20px;\n"
# "padding: 5px;")
        self.loginbutton.clicked.connect(self.login)
        self.loginbutton.setObjectName("loginbutton")
        self.loginbutton.clicked.connect(self.verify_connexion)
        self.logouser = QtWidgets.QLabel(self.leftpanel_2)
        self.logouser.setGeometry(QtCore.QRect(10, 190, 51, 51))
        self.logouser.setStyleSheet("color:rgb(116,116,116);")
        self.logouser.setText("")
        self.logouser.setPixmap(QtGui.QPixmap("fontawesome-free-6.7.2-desktop/svgs/solid/user.svg"))
        self.logouser.setScaledContents(True)
        self.logouser.setAlignment(QtCore.Qt.AlignCenter)
        self.logouser.setObjectName("logouser")
        self.errormessage = QtWidgets.QLabel(self.leftpanel_2)
        self.errormessage.setEnabled(True)
        self.errormessage.setGeometry(QtCore.QRect(10, 116, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errormessage.setFont(font)
        self.errormessage.setStyleSheet("color: red ;")
        self.errormessage.setText("")
        self.errormessage.setObjectName("errormessage")
        self.logouser_2 = QtWidgets.QLabel(self.leftpanel_2)
        self.logouser_2.setGeometry(QtCore.QRect(10, 290, 51, 51))
        self.logouser_2.setStyleSheet("color:rgb(116,116,116);")
        self.logouser_2.setText("")
        self.logouser_2.setPixmap(QtGui.QPixmap("fontawesome-free-6.7.2-desktop/svgs/solid/lock.svg"))
        self.logouser_2.setScaledContents(True)
        self.logouser_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logouser_2.setObjectName("logouser_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signinbutton.setText(_translate("MainWindow", "sign in"))
        self.label_5.setText(_translate("MainWindow", "hollydays in order"))
        self.label.setText(_translate("MainWindow", "connexion"))
        self.label_2.setText(_translate("MainWindow", "username"))
        self.label_3.setText(_translate("MainWindow", "password"))
        self.label_4.setText(_translate("MainWindow", "forgot password"))
        self.loginbutton.setText(_translate("MainWindow", "login"))

       




class connexion(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(connexion, self).__init__(parent)
        
        self.setupUi(self)
        
        self.loginbutton.clicked.connect(self.login)
        self.signinbutton.clicked.connect(self.signin)

    def save_clicked(self):
        print(f'class connexion: def save_clicked(self):')
    
    def verify_connexion(self):
        username = self.username.text()
        password = self.password.text()
        if username.strip() == "" and password.strip() =="":
             er = True   
             messa = "please fill field"
        else :    
                if model.is_user(username,password) == 1:
                        messa ="connexion reussie"
                        er = False
                        self.close()
                        self.w = main(username)
                        self.w.show()
                elif model.is_user(username,password) == -1:
                        messa = "incorect password"    
                        er = True         
                        self.errormessage.setText(" le mot de passe est incorect ")      
                else :
                        er = True         
                        messa = f"Uknow username "
           
        self.e = error(messa,er)
        self.e.exec_()

    def login(self):
        self.verify_connexion()
    def signin(self):
        self.close()
        self.windo = generateind.genaration()
        self.windo.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
